### ISSUE TITLE
Averaging models from biological replicates actually just takes either libA or libB score

### ISSUE THREAD

**Issue by fwelsh** [dms-vep/dms-vep-pipeline#168] opened 2023-09-26 18:15 UTC
**Note that this is for dms-vep-pipeline v2, [@77274ab](https://github.com/dms-vep/dms-vep-pipeline/tree/77274abf6a2135e7cfdc7ab1ad932abb870199ca)

Currently, the averaged models use an escape score either from libA or libB, rather than averaging these scores together.  I had originally set the escape_average_method as 'median' in [data/config.yaml](https://github.com/dms-vep/flu_h3_hk19_dms/blob/validations/config.yaml), but tried adjusting to 'mean' to see if this would fix the bug, and it did not. Pipeline re-run with 'mean' averaging is currently on branch (validations)[https://github.com/dms-vep/flu_h3_hk19_dms/tree/validations], and 'median' averaging is on main.

Note that I only run one replicate per library. The two libraries are not run at identical concentrations, which may be contributing to the error? Let me know if you have any questions @jbloom

**Comment by jbloom** [comment] 2023-09-28 22:46
@fwelsh, this is not a bug. This is because you have the average method set to `min_magnitude` (see [here](https://github.com/dms-vep/flu_h3_hk19_dms/blob/main/data/polyclonal_config.yaml#L7)), so it takes the minimum magnitude value across libraries.

This is a confusing aspect of `dms-vep-pipeline` that is fixed in `dms-vep-pipeline-3`. There is an average method set in both `config.yaml` and `polyclonal_config.yaml`, and the latter will override the former. Since you are using the older pipeline, just update the average method in `polyclonal_config.yaml` too.

Let me know if this fixes the problem. If so, please close this issue. If not, can you report back and I'll look more.

**Comment by fwelsh** [comment] 2023-09-28 23:06
Makes sense, thanks for looking into this! Re-running now with the updated pipeline

**Comment by fwelsh** [comment] 2023-09-29 18:03
Editing avg method in `polyclonal_config.yaml` fixed the problem

**Closed** 2023-09-29 18:02 UTC
